apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-deployment
  labels:
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec: 
      containers:
        - name: worker
          image: faisalsulhan/multi-worker
          env: 
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'

